### ISSUE TITLE
Maquetacion pagina de login

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#1]
Maquetar la pagina de login utilizando el template https://startbootstrap.com/template/sb-admin

Estima: 1h

Preview:
![image](https://github.com/opendhs/opendhs/assets/41107774/a79a7c80-1d34-4ff7-9498-054bc37843c9)

**Comment by yrodez** [comment]
Pon las horas reales en un mentario aqui al final

**Comment by grettelHdez** [comment]
Horas efectivas: 15h
