### ISSUE TITLE
Implementar la navegacion a la pagina Index a partir de la imagen. Eliminar el boton.

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#19]
![image](https://github.com/opendhs/opendhs/assets/41107774/b9adaf57-d017-4b02-b03f-6db0320de9a5)

**Comment by HurshelDeSouza** [comment]
tiempo estimado 2 horas

**Comment by HurshelDeSouza** [comment]
tiempo efectivo 1hora
