### ISSUE TITLE
Maquetacion pagina de registro usuarios

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#2]
Maquetar la pagina de registro usuario utilizando el template https://startbootstrap.com/template/sb-admin

Estima: 1h

Preview: 
![image](https://github.com/opendhs/opendhs/assets/41107774/617d486a-18bd-4abf-b4fc-fadc684f3cb3)

**Comment by grettelHdez** [comment]
Horas efectivas: 1h
