### ISSUE TITLE
Utilizar el logo en lugar del texto en la navbar

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#20]
Path Logo : wwwroot/asserts/img/bio/logo.png

![image](https://github.com/opendhs/opendhs/assets/41107774/00c5ebf7-7221-4c83-a277-5307b1606f80)

**Comment by HurshelDeSouza** [comment]
tiempo estimado 2 horas

**Comment by HurshelDeSouza** [comment]
tiempo efectivo 1 hora
