### ISSUE TITLE
Migracion de maquetacion html a razor pages

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#5]
Existe una primera version del sitio en la carpeta wwwroot.

index.html
contact.html
offer.html
team.html

Estas paginas en modo basico deben de ser migracas a la version razor pages (cshtml/cshtml.ch)

*Como ves ya casi todas estan puestas en cshtml

![image](https://github.com/opendhs/opendhs/assets/41107774/2e6be747-e862-4672-b180-30fe69df875c)

**Comment by HurshelDeSouza** [comment]
Tiempo efectivo 2h
