### ISSUE TITLE
Agregar link a las respectivas paginas desde la pagina home(index)

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#6]
Agregar Link

Card "Il nostro team" => pagina Team
Card "Il nostro servizio" => pagina Offer
Card "Venite a trovarci" => pagina Contatto

![image](https://github.com/opendhs/opendhs/assets/41107774/89e8c791-baba-45c7-932c-fd7a3cc998de)

**Comment by HurshelDeSouza** [comment]
1h
