### ISSUE TITLE
Fijar size images en los cards de la pagina de contacto

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#7]
Ambos cards tienen dimensiones diferentes por tener contenidos diferentes.

Sin embargo de quiere que tengan un tamano fijo. 

![image](https://github.com/opendhs/opendhs/assets/41107774/bf629823-0f53-424c-9185-819f1ac5a77a)

**Comment by HurshelDeSouza** [comment]
A la hora de probar en diferentes pantallas me sigue dando problemas en las fotos de las card, en algunas pantallas se ve bien y en otras pantallas cambia de tamaño

**Comment by HurshelDeSouza** [comment]
Tiempo estimado 3 horas

**Comment by HurshelDeSouza** [comment]
tiempo efecivo 2 horas
