### ISSUE TITLE
Correccion de link a paginas html eliminadas

### ISSUE THREAD

**Issue by yrodez** [opendhs/opendhs#9]
Revisar los link de menus (Todas las paginas)
![image](https://github.com/opendhs/opendhs/assets/41107774/a9458f2d-f98f-441d-9683-ca0196f882fd)

Revisar y corregir los link de los breadcrumbs (Todas las paginas)
![image](https://github.com/opendhs/opendhs/assets/41107774/b4eb78af-2b97-4fff-95d5-136d5424a2bc)

Revisar y corregir los link en el footer (Todas las paginas)
![image](https://github.com/opendhs/opendhs/assets/41107774/6db4f1b4-06c9-4ce8-9b31-b8f02df7fcda)

**Comment by HurshelDeSouza** [comment]
Tiempo de estima 3 horas

**Comment by HurshelDeSouza** [comment]
Tiempo efectivo 2h
